version: '3'
services:
  web:
    build: .
    container_name: dashboard
    restart: always
    ports:
      - '8080'
    links:
      - firebase
    depends_on:
      - firebase
  firebase:
    container_name: firebase
    image: firebase
    ports:
      - '8080:8080'